### ISSUE TITLE
Reduce framework setup overhead each time

### ISSUE THREAD

**Issue by TjWallas** [BenjaminSchiller/SparkWrapper#2]
One way to do this is by to read multiple dynamic graph snapshots in one go.
- Investigate how feasible it is to read multiple snapshots of one graph in one run of `spark-shell`
- Concern 1: Will all snapshots fit into the main memory in addition to the memory consumption during the lifecycle of `n` jobs on each snapshot in `{1, ... n}`?
- According to the answers to the above two points, start (or not) implementing this feature.

**Comment by TjWallas** [comment]
@BenjaminSchiller To address `concern 1`, one would need to know:
1. How much memory is available on the system?
2. What is the maximum number of snapshots for a given dynamic graph?
3.  Roughly, how much memory does it take to store RDDs related to a graph of `k` nodes and `l` edges?
4. Compute `result(3) * result(2)`

If the above memory needs exceed the available memory on the system, it makes no sense to proceed further and profile memory consumption during running each graph algorithm `A`.

**Comment by BenjaminSchiller** [comment]
i assume that the whole process is not really restricted by the memory.
we do not need to read k times and then analyze the k read graph.
if would assume that we should rather to k x (read, analyze) and therefore will not have this problem....

**Comment by TjWallas** [comment]
@BenjaminSchiller I see.

Here is an alternative proposal. See if we can use `spark-submit` and run a spark master locally instead of `spark-shell`. This way we have roughly the same behavior of flink where the setup time is done only once in the beginning.
https://spark.apache.org/docs/latest/submitting-applications.html

_[Edit Thu Jul 21 15:39:15 CEST 2016 - @TjWallas]_ 
Packaging a scala file into a JAR for spark should be easy:
https://spark.apache.org/docs/latest/quick-start.html

**Comment by BenjaminSchiller** [comment]
sounds good!

**Comment by TjWallas** [comment]
@BenjaminSchiller Now, we run a single master and submit multiple jobs to it using `spark-submit`. Note the updated README.

If you have already installed everything on the p2p machine, below are the _new_ steps you need to perform:
- Install SBT 

``` bash
# SBT for scala packaging
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
sudo apt-get update
sudo apt-get install sbt
```
- Launch Spark master

``` bash
# Make sure JAVA_HOME is set first.
sudo /opt/spark-1.6.2-bin-hadoop2.6/sbin/start-master.sh
```
- Build application

``` bash
sbt package
```
- Submit job

``` bash
./submit_spark_job.sh <input_vertices_filepath> <input_edges_filepath> <output_filepath> <algorithm_id> <src_vertex_id_shortest_paths> <num_worker_threads>
```

**Comment by BenjaminSchiller** [comment]
nice, this should speedup the analysis :-D
